// Hand-drawn arrow shafts extracted from the curated reference set in
// public/res/docs/dashed_curved_arrows_final.svg (30 arrows generated by a
// cubic-bezier-sampling + jitter script). Picked for a wander-to-chord ratio
// near 1 (the path never strays farther from its own start than its own tip
// does) — that keeps the doodle proportional to whatever real distance it
// gets fitted to, instead of a loopy shape ballooning when scaled up.
//
// Each shaft is stored as a real multi-segment cubic-bezier `d` string (not
// the dense polyline the reference file uses) — refit from the original
// jittery sample points via a Catmull-Rom-through-key-points conversion, the
// same "single cubic bezier" principle as the original arrow generator, just
// piecewise where a curve loops back on itself enough to need more than one
// segment. A plain least-squares single-cubic fit was tried first but blew
// up into wild overshoot on the loopier templates (classic instability for
// high-curvature data); Catmull-Rom is local per segment, so it can't diverge
// like that, and it still passes through the original hand-drawn wobble.
//
// Each shaft is translated so its own start point sits at (0,0) — the rest
// of its geometry, including `tip` (the endpoint) and `prevTip` (the second
// control point of the final bezier segment, i.e. the exact point the exit
// tangent is drawn through), stays as fit. DocsFieldWalkthrough fits a shaft
// between two real page points by translating to the start, rotating so the
// shaft's own start→tip chord lines up with the real one, and scaling
// uniformly.
export interface ArrowTemplate {
  shaft: string;
  tip: { x: number; y: number };
  prevTip: { x: number; y: number };
}

export const ARROW_TEMPLATES: ArrowTemplate[] = [
  {
    shaft: "M 0 0 C 16.35 -8.81 34.57 -16.91 49.05 -26.44 C 63.53 -35.97 77.89 -46.54 86.9 -57.17 C 95.91 -67.8 100.13 -78.37 103.09 -90.2 C 106.05 -102.03 104.12 -115.5 104.64 -128.15",
    tip: { x: 104.64, y: -128.15 },
    prevTip: { x: 104.12, y: -115.50 },
  },
  {
    shaft: "M 0 0 C 15.38 3.28 32.02 5.07 46.14 9.84 C 60.26 14.61 73.02 20.83 84.71 28.63 C 96.4 36.43 106.82 46.46 116.27 56.63 C 125.72 66.8 134.55 79.29 141.39 89.65 C 148.23 100.01 152 109.08 157.3 118.8",
    tip: { x: 157.30, y: 118.80 },
    prevTip: { x: 152.00, y: 109.08 },
  },
  {
    shaft: "M 0 0 C -5.3 -13.73 -12.98 -26.87 -15.9 -41.19 C -18.82 -55.51 -18.71 -70.83 -17.54 -85.91 C -16.37 -100.99 -11.1 -116.83 -8.86 -131.66 C -6.62 -146.49 -4.37 -160.62 -4.11 -174.87 C -3.85 -189.12 -6.24 -203.06 -7.31 -217.16",
    tip: { x: -7.31, y: -217.16 },
    prevTip: { x: -6.24, y: -203.06 },
  },
  {
    shaft: "M 0 0 C 10.63 -11.72 27.37 -21.64 31.89 -35.17 C 36.41 -48.7 33.21 -67.09 27.14 -81.21 C 21.07 -95.33 3.88 -106.39 -4.55 -119.88 C -12.98 -133.37 -23.37 -147.25 -23.44 -162.15 C -23.51 -177.05 -11.11 -193.55 -4.95 -209.25",
    tip: { x: -4.95, y: -209.25 },
    prevTip: { x: -11.11, y: -193.55 },
  },
  {
    shaft: "M 0 0 C -14.32 14.07 -27.89 31 -42.96 42.2 C -58.03 53.4 -75.4 63.79 -90.44 67.21 C -105.48 70.63 -121.98 68.37 -133.22 62.73 C -144.45 57.09 -154.31 44.5 -157.85 33.35 C -161.39 22.2 -155.58 8.33 -154.44 -4.18",
    tip: { x: -154.44, y: -4.18 },
    prevTip: { x: -155.58, y: 8.33 },
  },
  {
    shaft: "M 0 0 C 16.09 -2.64 33.44 -3.11 48.28 -7.93 C 63.13 -12.75 78.39 -20.97 89.07 -28.93 C 99.75 -36.89 107.13 -46.34 112.38 -55.69 C 117.63 -65.04 117.83 -75.25 120.56 -85.03",
    tip: { x: 120.56, y: -85.03 },
    prevTip: { x: 117.83, y: -75.25 },
  },
  {
    shaft: "M 0 0 C -9.11 10.83 -23.04 20.32 -27.34 32.48 C -31.64 44.64 -31.32 61.47 -25.8 72.94 C -20.28 84.41 -4.73 91.85 5.8 101.3",
    tip: { x: 5.80, y: 101.30 },
    prevTip: { x: -4.73, y: 91.85 },
  },
  {
    shaft: "M 0 0 C 14.81 -11.8 29.13 -27.92 44.42 -35.41 C 59.71 -42.89 76.42 -46.09 91.73 -44.91 C 107.05 -43.73 122.44 -35.98 136.31 -28.35 C 150.19 -20.72 162.19 -5.92 174.98 0.89 C 187.76 7.7 200.34 8.64 213.02 12.52",
    tip: { x: 213.02, y: 12.52 },
    prevTip: { x: 200.34, y: 8.64 },
  },
];
